### ISSUE TITLE
Guzzle version

### ISSUE THREAD

**Issue by aistis-** [hglattergotz/pardot#2]
Hey guys, do you plan to update guzzle client to v6?

**Comment by hglattergotz** [comment]
Hi aistis,

Is this causing a dependency issue/conflict for you?
I would be happy to help move this forward. Unfortunately I no longer have access to an actual Pardot account (client switched providers), so I would need help with testing.
U up for that?

**Comment by aistis-** [comment]
It does not conflict, just though it would nice to avoid another dependency in my app :) anyway, it and works as expected :+1:

**Comment by hglattergotz** [comment]
Ok, good deal.
